apiVersion: apps/v1
kind: Deployment
metadata:
  name: used-car-marketplace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: used-car-marketplace
  template:
    metadata:
      labels:
        app: used-car-marketplace
    spec:
      containers:
      - name: app
        image: used-car-marketplace:latest
        ports:
        - containerPort: 80
